### ISSUE TITLE
Crash on export to SMB2 compressed LZ

### ISSUE THREAD

**Issue by MandL27** [CraftedCart/SMBLevelWorkshop#4]
So I get [this error](https://cdn.discordapp.com/attachments/238040800070598656/281246628386701313/unknown.png) every time I try exporting a level to SMB2 compressed LZ. It runs just fine up until then, and I have made sure the source .obj is triangulated.

**Comment by MandL27** [comment]
Never mind; figured out the issue. Blender triangulation breaks Workshop for some reason.

**Comment by CraftedCart** [comment]
Not triangulating shouldn't break it, and Blender's triangulation works fine for me. Huh?

**Comment by CraftedCart** [comment]
Either way, a bad OBJ or a bad OBJ reader (I just used someone else's reader) shouldn't crash it so I'm reopening this. At worst, this should just fail exporting.

**Comment by MandL27** [comment]
Just confirmed that it wasn't Blender's triangulation breaking it, it was textures not being next to the .obj that broke it. In other words, if you have textures on the level model but it appears untextured in Workshop, exporting to .lz can and will crash.

**Comment by CraftedCart** [comment]
Ah thanks

**Comment by MandL27** [comment]
I would mention that this mirrors behavior in GxModelViewer, but if you're going to add GMA/TPL exporting that isn't exactly relevant. :p
